Models/Milk.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
namespace MilkShop.Models
{
    public class Milk
    {
        public int Id { get; set; }
        [Display(Name = "Tên sữa")]
        public string Title { get; set; }
        [Display(Name = "Ngày sản xuất")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        [Display(Name = "Hãng sữa")]
        public string Genre { get; set; }
        [Display(Name ="số lượng")]
        public string Rating { get; set; }
        [Display(Name = "Giá bán")]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
    }
}

Controllers/MilkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MilkShop.Data;
using MilkShop.Models;

namespace MilkShop.Controllers
{
    public class MilkController : Controller
    {
        private readonly MilkShopContext _context;

        public MilkController(MilkShopContext context)
        {
            _context = context;
        }

        // GET: Milk
        public async Task<IActionResult> Index(string milkGenre, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from b in _context.Milk
                                            orderby b.Genre
                                            select b.Genre;
            var milks = from b in _context.Milk
                        select b;
            if (!string.IsNullOrEmpty(searchString))
            {
                milks = milks.Where(s => s.Title!.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(milkGenre))
            {
                milks = milks.Where(x => x.Genre == milkGenre);
            }
            var milkGenreVM = new MilkGenreViewModel
            {
                Genres = new SelectList(await
           genreQuery.Distinct().ToListAsync()),
                Milks = await milks.ToListAsync()
            };
            return View(milkGenreVM);
        }


        // GET: Milk/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milk = await _context.Milk
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milk == null)
            {
                return NotFound();
            }

            return View(milk);
        }

        // GET: Milk/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Milk/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Genre,Price,Rating")] Milk milk)
        {
            if (ModelState.IsValid)
            {
                _context.Add(milk);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(milk);
        }

        // GET: Milk/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milk = await _context.Milk.FindAsync(id);
            if (milk == null)
            {
                return NotFound();
            }
            return View(milk);
        }

        // POST: Milk/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price,Rating")] Milk milk)
        {
            if (id != milk.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(milk);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MilkExists(milk.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(milk);
        }

        // GET: Milk/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milk = await _context.Milk
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milk == null)
            {
                return NotFound();
            }

            return View(milk);
        }

        // POST: Milk/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var milk = await _context.Milk.FindAsync(id);
            _context.Milk.Remove(milk);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MilkExists(int id)
        {
            return _context.Milk.Any(e => e.Id == id);
        }
    }
}

Views/Milk/Create.cshtml
@model MilkShop.Models.Milk

@{
    ViewData["Title"] = "Tạo sản phẩm mới";
}

<h1>Tạo sản phẩm mới</h1>

<h4>Milk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Tên sữa</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label">Ngày sản xuất</label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label">Hãng sữa</label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label">Giá bán</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Milk/Delete.cshtml
@model MilkShop.Models.Milk

@{
    ViewData["Title"] = "Xoá sản phẩm";
}

<h1>Xoá sản phẩm</h1>

<h3>Bạn có chắc là xoá sản phẩm này không ?</h3>
<div>
    <h4>Milk</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Tên sữa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            Ngày sản xuất
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            Hãng sữa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            Giá bán
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xoá" class="btn btn-danger" /> |
        <a asp-action="Index">Quay lại</a>
    </form>
</div>

Views/Milk/Details.cshtml
@model MilkShop.Models.Milk

@{
    ViewData["Title"] = "Chi tiết";
}

<h1>Chi tiết sản phẩm</h1>

<div>
    <h4>Milk</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Tên sữa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            Ngày sản xuất
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            Hãng sữa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            Giá bán
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">sửa</a> |
    <a asp-action="Index">Quay lại</a>
</div>

Views/Milk/Edit.cshtml
@model MilkShop.Models.Milk

@{
    ViewData["Title"] = "Sửa sản phẩm";
}

<h1>Sửa sản phẩm</h1>

<h4>Milk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label">Tên sữa</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label">Ngày sản xuất</label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label">Hãng sữa</label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Giá bán</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu sản phẩm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Milk/Index.cshtml
@model MilkShop.Models.MilkGenreViewModel

@{
    ViewData["Title"] = "Thêm Sản Phẩm";
}

<h1>Thêm Sản Phẩm</h1>

<p>
    <a asp-action="Create"> Đặt hàng</a>
</p>
<form asp-controller="Milk" asp-action="Index" method="get">
    <p>
        <select asp-for="MilkGenre" asp-items="Model.Genres">
            <option value="">Hãng sữa</option>
        </select>

        Sản phẩm : <input type="text" name="SearchString" />
        <input type="submit" value="Tìm kiếm" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Milks[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Milks[0].ReleaseDate)
                
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Milks[0].Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Milks[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Milks[0].Rating)

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Milks)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Xoá</a>
            </td>
        </tr>
        }
    </tbody>
</table>